# Generated by Django 4.2.4 on 2023-09-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_revision_doc_appuser_disipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=50)),
                ('revision_actuelle', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.projet')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_revision', models.CharField(max_length=10)),
                ('fichier', models.FileField(upload_to='revisions/')),
                ('commentaire', models.TextField()),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.document')),
            ],
        ),
    ]
